### ISSUE TITLE
Add tag decoration

### ISSUE THREAD

**Issue by grzkv** [bookingcom/nanotube#6]
We need the ability to decorate some of the incoming records with tags. This can be useful for adding API keys or contextual information.

This can be implemented either by regex or for all records. It makes sense to make it part of rewrite rules in the first case. In that case, it may look something like:

```toml
[[tag]]
for = "abc*"
tag = "tagname"
copy = true
```
